# Generated by Django 2.1.3 on 2018-11-17 19:37

from django.db import migrations, models
import django.db.models.deletion
import lesson.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Төлөв')),
                ('title', models.CharField(max_length=50, verbose_name='Гарчиг')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Хаяг')),
                ('class_number', models.IntegerField(null=True, verbose_name='Анги')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Хичээлийн текст')),
                ('cover', sorl.thumbnail.fields.ImageField(null=True, upload_to=lesson.models.cover_upload, verbose_name='Зураг')),
            ],
            options={
                'verbose_name': 'Нийтлэл',
                'verbose_name_plural': 'Нийтлэлүүд',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Төлөв')),
                ('name', models.CharField(max_length=50, verbose_name='Хичээлийн нэр')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Хаяг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
            ],
            options={
                'verbose_name': 'Хичээл',
                'verbose_name_plural': 'Хичээлүүд',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Төлөв')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гарчиг')),
                ('question', models.CharField(blank=True, max_length=100, null=True, verbose_name='Асуулт')),
                ('answer_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Хариулт-1')),
                ('answer_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Хариулт-2')),
                ('answer_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Хариулт-3')),
                ('right_answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зөв хариулт')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='lesson.Article')),
            ],
            options={
                'verbose_name': 'Сорил',
                'verbose_name_plural': 'Сорилууд',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='lesson.Subject'),
        ),
    ]
