# Generated by Django 2.0 on 2018-11-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Гарчиг')),
                ('answer_1', models.CharField(max_length=100, verbose_name='Асуулт-1')),
                ('answer_2', models.CharField(max_length=100, verbose_name='Асуулт-2')),
                ('answer_3', models.CharField(max_length=100, verbose_name='Асуулт-3')),
                ('right_answer', models.CharField(max_length=100, verbose_name='Зөв хариулт')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Хичээлийн нэр')),
                ('class_number', models.IntegerField(null=True, verbose_name='Ангийн тоо')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Гарчиг')),
                ('text', models.TextField(max_length=1000, null=True, verbose_name='Хичээлийн текст')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Асуулт')),
                ('title', models.CharField(max_length=50, verbose_name='Гарчиг')),
            ],
        ),
    ]
