# Generated by Django 2.0 on 2018-11-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Төлөв')),
                ('question', models.CharField(blank=True, max_length=100, null=True, verbose_name='Асуулт')),
                ('answer_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Хариулт-1')),
                ('answer_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Хариулт-2')),
                ('answer_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Хариулт-3')),
                ('right_answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зөв хариулт')),
            ],
            options={
                'verbose_name': 'Асуулт',
                'verbose_name_plural': 'Асуултууд',
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.RemoveField(
            model_name='test',
            name='right_answer',
        ),
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Хаяг'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test', to='lesson.Test'),
        ),
    ]
